# Generated by Django 4.2.1 on 2023-07-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseRental', '0002_alter_property_propstatus_alter_room_roomstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='ownName',
            field=models.CharField(max_length=50),
        ),
    ]
